/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Korisnik;
import model.ModelZemlja;
import model.Prijava;
import model.Stanovnik;
import model.Stavka;
import model.Zemlja;
import transfer.KlijentZahtev;

/**
 *
 * @author USER
 */
public class PrijavaNeregistrovan extends javax.swing.JFrame {

    /**
     * Creates new form PrijavaNeregistrovan
     */
    private ModelZemlja mz;
    public PrijavaNeregistrovan() {
        initComponents();
        setTitle("Prijava putovanja - neregistrovan");
        setLocationRelativeTo(null);
        komunikacija.Komunikacija.getInstance().posalji(new KlijentZahtev(operacije.Operacije.vrati_z, ""));
        for(Zemlja z:(List<Zemlja>)komunikacija.Komunikacija.getInstance().procitaj().getOdg())
        {
           jComboBox2.addItem(z);
        }
        mz=new ModelZemlja(new ArrayList<>());
        jTable_z.setModel(mz);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField_jmbg = new javax.swing.JTextField();
        jTextField_bp = new javax.swing.JTextField();
        jTextField_du = new javax.swing.JTextField();
        jTextField_di = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_z = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel4.setText("Datum ulaska(dd.MM.yyyy.):");

        jLabel5.setText("Datum izlaska(dd.MM.yyyy.):");

        jLabel6.setText("Broj pasosa:");

        jLabel7.setText("Nacin putovanja:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Putnicki automobil", "Motocikl", "Autobus", "Avio prevoz" }));

        jLabel8.setText("Zemlja/zemlje putovanja:");

        jTable_z.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Unete zemlje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_z.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable_z);
        jTable_z.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("Dodaj zemlju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Obrisi zemlju");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Prijavi putovanje");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_jmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jTextField_bp, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jTextField_du, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jTextField_di, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(2, 2, 2)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_jmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_bp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_du, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_di, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(postojepraznapolja())
        {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna!");return ;
        }
        String v=formatpolja();
        if(!v.equals("ok"))
        {
            JOptionPane.showMessageDialog(this, v);return ;
        }
        v=validacijaJedinstvenih();
        if(!v.equals("ok"))
        {
            JOptionPane.showMessageDialog(this, "\nVec postoji profil sa datim podacima\nUlogujte se!");return ;
        }        
        if(mz.getL().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Prijava mora imati bar jednu zemlju");return ;
        }
        
        Date du=null, di=null;
        try {
            du=new SimpleDateFormat("dd.MM.yyyy.").parse(jTextField_du.getText());
            di=new SimpleDateFormat("dd.MM.yyyy.").parse(jTextField_di.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los format datuma ulaska i/ili izlaska");return  ;
        }

        Date d=new Date();
        SimpleDateFormat format=new SimpleDateFormat("dd.MM.yyyy.");
        try {
            d=format.parse(format.format(d));
        } catch (ParseException ex) {
            Logger.getLogger(Izmena.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(du.compareTo(d)<0)
        {
            JOptionPane.showMessageDialog(this, "Datuma ulaska ne sme da bude pre danasnjeg");return  ;
        }
        if(di.before(du))
        {
            JOptionPane.showMessageDialog(this, "Datuma izlaska ne sme da bude pre datuma ulaska");return  ;
        }
        
        Date dicist=null;
        Date ducist=null;
         try {
            ducist=format.parse(format.format(du));
            dicist=format.parse(format.format(di));
        } catch (ParseException ex) {
            Logger.getLogger(PrijavaNeregistrovan.class.getName()).log(Level.SEVERE, null, ex);
        }
        int brdana=(int) ((dicist.getTime()-ducist.getTime())/1000/60/60/24);
        if(brdana>90)
        {
            JOptionPane.showMessageDialog(this, "Korisnik moze da se zadrzi maksimalno 90 dana na putu");return  ;
        }

        Prijava p=new Prijava(-1, new Stanovnik(-1, jTextField1.getText(),jTextField2.getText(), jTextField_jmbg.getText(), jTextField_bp.getText(), null), du, di, (String) jComboBox1.getSelectedItem());
        List<Stavka>l=new ArrayList<>();
        for(Zemlja z:mz.getL())
        {
            l.add(new Stavka(p, z));
        }
        komunikacija.Komunikacija.getInstance().posalji(new KlijentZahtev(operacije.Operacije.proveraPutovanja, l));
        if(!(boolean)komunikacija.Komunikacija.getInstance().procitaj().getOdg())
        {
            JOptionPane.showMessageDialog(this, "Vec imate prijavljeno putovanje u tom periodu za neku od zemalja");return ;
        }
        komunikacija.Komunikacija.getInstance().posalji(new KlijentZahtev(operacije.Operacije.sacuvaj_prijavu, l));
        if((boolean)komunikacija.Komunikacija.getInstance().procitaj().getOdg())
        {
            System.out.println((String)komunikacija.Komunikacija.getInstance().procitaj().getOdg());
           JOptionPane.showMessageDialog(this, "Uspesno sacuvana prijava");return ;
         }
        JOptionPane.showMessageDialog(this, "Neuspesno sacuvana prijava");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(mz.getL().contains((Zemlja)jComboBox2.getSelectedItem()))return ;
        mz.getL().add((Zemlja) jComboBox2.getSelectedItem());
        mz.fireTableDataChanged();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int r=jTable_z.getSelectedRow();
        if(r==-1)return ;
        mz.getL().remove(r);
        mz.fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean postojepraznapolja() {
        if(jTextField1.getText().isBlank() || jTextField2.getText().isBlank()|| jTextField_jmbg.getText().isBlank() || jTextField_bp.getText().isBlank()  || jTextField_jmbg.getText().isBlank() || jTextField_bp.getText().isBlank())
            return true;
        return false;
    }

    private String validacijaJedinstvenih() {
        String user="";
        String jmbg=jTextField_jmbg.getText().trim();
        String bp=jTextField_bp.getText().trim();
        komunikacija.Komunikacija.getInstance().posalji(new KlijentZahtev(operacije.Operacije.validacijaJedinstvenih, new String[]{user, jmbg, bp}));
        return (String)komunikacija.Komunikacija.getInstance().procitaj().getOdg();
    }

    private String formatpolja()
    {
        String jmbg=jTextField_jmbg.getText();
        String bp=jTextField_bp.getText();
         List<String>greske=new ArrayList<>();
//        provera jmbg-a
        if(jmbg.length()!=13 )greske.add( "JMBG mora da ima tacno 13 cifara");
        for(Character c:jmbg.toCharArray())
        {
            if(!Character.isDigit(c))greske.add( "JMBG sme da sadrzi samo cifre");
        }
        int dan=Integer.parseInt(jmbg.substring(0, 2));
        int mesec=Integer.parseInt(jmbg.substring(2, 4));
        int godina=Integer.parseInt(jmbg.substring(4, 7));
        if(godina>=900)godina+=1000;
        else godina+=2000;
        try {
            new SimpleDateFormat("dd.MM.yyyy.").parse(dan+"."+mesec+"."+godina+".");
        } catch (Exception e) {
            System.out.println(jmbg);
            greske.add("nije dobar format jmgba");
        }

//        provera broja pasosa
        if(bp.length()!=9 )greske.add("Broj pasosa mora da ima tacno 9 cifara");
        for(Character c:bp.toCharArray())
        {
            if(!Character.isDigit(c))greske.add("Broj pasosa sme da sadrzi samo cifre");
        }
        if(!greske.isEmpty())return String.join("\n", greske);
    return "ok";
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Zemlja> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_z;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_bp;
    private javax.swing.JTextField jTextField_di;
    private javax.swing.JTextField jTextField_du;
    private javax.swing.JTextField jTextField_jmbg;
    // End of variables declaration//GEN-END:variables

 }
